# Generated by Django 2.2.10 on 2021-06-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateTimeField(help_text='Учтите, после заполнения даты, изменить опрос вы не сможете.', verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('Один выбранный вариант', 'Один выбранный вариант'), ('Несколько выбранных вариантов', 'Несколько выбранных вариантов'), ('Свой вариант ответа', 'Свой вариант ответа')], max_length=55, verbose_name='Тип вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques.Poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='QuesChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, verbose_name='Описание выбора')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ques.Question')),
            ],
        ),
    ]
