# Generated by Django 2.2.10 on 2021-06-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0003_auto_20210618_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queschoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_choices', to='ques.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='ques.Poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('one', 'Один выбранный вариант'), ('many', 'Несколько выбранных вариантов'), ('text', 'Свой вариант ответа')], help_text='Если вы выбрали один или несколько вариантов ответа, заполните поля "описание выбора",если вы выбрали "свой вариант ответа", не заполняйте это поле', max_length=55, verbose_name='Тип вопроса'),
        ),
    ]
