# Generated by Django 2.2.10 on 2021-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0004_auto_20210619_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Один выбранный вариант', 'Один выбранный вариант'), ('Несколько выбранных вариантов', 'Несколько выбранных вариантов'), ('Свой вариант ответа', 'Свой вариант ответа')], help_text='Если вы выбрали один или несколько вариантов ответа, заполните поля "описание выбора",если вы выбрали "свой вариант ответа", не заполняйте это поле', max_length=55, verbose_name='Тип вопроса'),
        ),
    ]
