# Generated by Django 2.2.10 on 2021-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0005_auto_20210619_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswerques',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
