# Generated by Django 2.2.10 on 2021-06-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques', '0006_auto_20210619_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userid',
            options={'verbose_name': 'Опрос пользователей', 'verbose_name_plural': 'Опросы пользователей'},
        ),
        migrations.AlterField(
            model_name='useranswerques',
            name='ques_choices',
            field=models.ManyToManyField(blank=True, null=True, to='ques.QuesChoices'),
        ),
    ]
